# Generated by Django 5.1.6 on 2025-03-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinspect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
